#!/usr/bin/env python3
# gPodder Android QRC Build Script
# Based on: gPodder Windows Build Script 2014-02-22
# 2014-11-07 Thomas Perl <thp.io/about>
# All rights reserved.

import os

IGNORED_FILES = ['common']

# Can be touch or desktop at the moment
variant = 'touch'

def mount_files(out, source, target):
    if os.path.isfile(source):
        from_filename = source
        to_filename = target
        print('<file alias="%s">%s</file>' % (to_filename, from_filename), file=out)
        print(from_filename, '->', to_filename)
        return

    for path, dirnames, filenames in os.walk(source):
        path = path.replace('\\', '/')
        for filename in sorted(filenames):
            if filename in IGNORED_FILES:
                continue

            from_filename = '/'.join((path, filename))
            to_filename = from_filename.replace(source, target)
            print('<file alias="%s">%s</file>' % (to_filename, from_filename), file=out)
            print(from_filename, '->', to_filename)

with open('gpodder.qrc', 'w') as out:
    print('<RCC>', file=out)
    print('<!-- Generated by {}, do not edit -->'.format(__file__), file=out)
    print('<qresource prefix="/">', file=out)

    # QML UI
    mount_files(out, 'gpodder-ui-qml/%s' % variant, variant)
    mount_files(out, 'gpodder-ui-qml/common', '%s/common' % variant)
    mount_files(out, 'gpodder-ui-qml/main.py', 'main.py')
    mount_files(out, 'podcastparser/podcastparser.py', 'podcastparser.py')
    mount_files(out, 'gpodder-core/src/gpodder', 'gpodder')

    print('</qresource>', file=out)
    print('</RCC>', file=out)
