/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gpodder_android_GPodderNative */

#ifndef _Included_org_gpodder_android_GPodderNative
#define _Included_org_gpodder_android_GPodderNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gpodder_android_GPodderNative
 * Method:    audioBecomingNoisy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gpodder_android_GPodderNative_audioBecomingNoisy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
